[project]
name = "fastapi-fundamentals"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Hugo Arevalo", email = "gohulu@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "fastapi[all,standard]>=0.141.1",
    "passlib[bcrypt]>=1.7.4",
    "sqlmodel>=0.0.42",
]

[project.scripts]
fastapi-fundamentals = "fastapi_fundamentals:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
