[project]
name = "fastapi-fundamentals"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Hugo Arevalo", email = "gohulu@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "bcrypt<4.1",
    "fastapi[all,standard]>=0.141.1",
    "passlib>=1.7.4",
    "sqlmodel>=0.0.42",
]

[project.scripts]
fastapi-fundamentals = "fastapi_fundamentals:main"
create-user = "fastapi_fundamentals.create_user:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
